import { BuiltArtifactSchema, type CodeBlueprint } from "../../domain/index.js";
import type { ArtifactBuilder } from "./types.js";

const BUILDER_VERSION = "1.0.0";

function renderModule(blueprint: CodeBlueprint, mod: CodeBlueprint["modules"][number]): string {
  const exportsList = mod.exports.length ? mod.exports.join(", ") : "none";
  const exportStatements = mod.exports.length
    ? mod.exports.map((name) => `export const ${name} = "${blueprint.promptId}:${name}";`).join("\n")
    : `export const ${mod.id}_entry = "${blueprint.promptId}:${mod.id}";`;

  return [
    `// Generated by PromptFarm deterministic code builder v${BUILDER_VERSION}`,
    `// Prompt: ${blueprint.promptId}`,
    `// Module: ${mod.id}`,
    `// Purpose: ${mod.purpose}`,
    `// Declared exports: ${exportsList}`,
    "",
    exportStatements,
    "",
  ].join("\n");
}

export const codeBuilder: ArtifactBuilder<CodeBlueprint> = {
  artifactType: "code",
  build: (blueprint) =>
    BuiltArtifactSchema.parse({
      promptId: blueprint.promptId,
      artifactType: blueprint.artifactType,
      builderVersion: BUILDER_VERSION,
      files: blueprint.modules.map((mod) => ({
        path: mod.path,
        mediaType: "text/typescript",
        content: renderModule(blueprint, mod),
      })),
      metadata: {
        moduleCount: blueprint.modules.length,
      },
    }),
};

